# Generated by Django 6.0.5 on 2026-06-28 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderdetail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='ordered_data',
            new_name='ordered_date',
        ),
    ]
